### PR TITLE
Meticulous changes (row33 and beyond)

### PR DESCRIPTION
**Pull request by XCOM-HUB**
Updated descriptions and events for artifacts in game.json.

Uppdaterade beskrivningar och händelser för artefakter i game.json

### CODE REVIEW

**Comment by XCOM-HUB** [comment]
Come check my latest Pull Request @misiokles , @heroesiiifan , @Fabrice-TIERCELIN !!!

**Comment by Fabrice-TIERCELIN** [comment]
Hi @XCOM-HUB,

I haven't the rights for merging.

Please give us all the translations that you can't write on your own, like the text on the _Adventure Option Menu_.

**Comment by XCOM-HUB** [comment]
Sure, I can do that @Fabrice-TIERCELIN. Do you want me to write it in "Issues", or should I just give you the translations here in this comment section?

**Comment by Fabrice-TIERCELIN** [comment]
Creating issues seems more suitable

**Pull request merged**
